root = "."
#tmp_dir = "/tmp"

[build]
cmd = "GOFLAGS=-buildvcs=false go build -o /tmp/main ./cmd/command_server"
bin = "/tmp/main"
include_ext = ["go", "mod", "sum", "tpl", "tmpl"]
exclude_dir = ["docker", "cmd/query_server", "test", "internal/app/query"]
send_interrupt = true
#rerun = true
#rerun_delay = 1000
stop_on_error = true

[misc]
# Delete tmp directory on exit
clean_on_exit = true