
services:
  mailer-command-db:
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U rashop -d rashop-mailer" ]
      interval: 5s
      retries: 10
    environment:
      - POSTGRES_DB=rashop-mailer
      - POSTGRES_USER=rashop
      - POSTGRES_PASSWORD=rashop123
    ports:
      - "5432:5432"
  mailer-query-db:
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U rashop -d rashop-mailer" ]
      interval: 5s
      retries: 10
    environment:
      - POSTGRES_DB=rashop-mailer
      - POSTGRES_USER=rashop
      - POSTGRES_PASSWORD=rashop123
    ports:
      - "5433:5432"
  jaeger:
    image: jaegertracing/all-in-one:1.58
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9090:8080
    depends_on:
      - broker
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      DYNAMIC_CONFIG_ENABLED: 'true'
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:7.5.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
  mailer-command-migrate:
    build:
      context: ../../
      dockerfile: docker/migrate.Dockerfile
      args:
        SERVICE: mailer
    restart: on-failure
    depends_on:
      mailer-command-db:
        condition: service_healthy
    environment:
      - PG_ADDRESS=mailer-command-db
      - PG_USERNAME=rashop
      - PG_PASSWORD=rashop123
      - PG_DB_NAME=rashop-mailer
      - PG_IS_SECURE=false
  mailer-query-migrate:
    build:
      context: ../../
      dockerfile: docker/migrate.Dockerfile
      args:
        SERVICE: mailer
    restart: on-failure
    depends_on:
      mailer-query-db:
        condition: service_healthy
    environment:
      - PG_ADDRESS=mailer-query-db
      - PG_USERNAME=rashop
      - PG_PASSWORD=rashop123
      - PG_DB_NAME=rashop-mailer
      - PG_IS_SECURE=false
  mailer-command-HR-server:
    image: cosmtrek/air
    depends_on:
      mailer-command-migrate:
        condition: service_completed_successfully
    working_dir: /mini-shop/services/mailer
    command: ["-c", "../../.command.air.toml"]
    env_file:
      - dev.env
    environment:
      - PG_ADDRESS=mailer-command-db
      - PG_USERNAME=rashop
      - PG_PASSWORD=rashop123
      - PG_DB_NAME=rashop-mailer
      - OTLP_GRPC_COLLECTOR_ADDRESS=jaeger:4317
      - BROKER_ADDRESSES=broker:29092
      - BROKER_GROUP_ID=mailer-command
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ../../:/mini-shop/
  mailer-query-HR-server:
    image: cosmtrek/air
    depends_on:
      mailer-query-migrate:
        condition: service_completed_successfully
    working_dir: /mini-shop/services/mailer
    command: [ "-c", "../../.query.air.toml" ]
    environment:
      - PG_ADDRESS=mailer-query-db
      - PG_USERNAME=rashop
      - PG_PASSWORD=rashop123
      - PG_DB_NAME=rashop-mailer
      - OTLP_GRPC_COLLECTOR_ADDRESS=jaeger:4317
      - BROKER_ADDRESSES=broker:29092
      - BROKER_GROUP_ID=mailer-query
    ports:
      - "8082:8080"
      - "8083:8081"
    volumes:
      - ../../:/mini-shop/

networks:
  default:
    driver: bridge